// 自動生成ファイル。直接編集しない。
// 生成元: assets/color_master.json
// 再生成: npm run sync-color-ids
export const COLOR_IDS = [
  "coral_pink",
  "apricot",
  "peach",
  "cream_yellow",
  "fresh_green",
  "turquoise",
  "ivory",
  "light_orange",
  "salmon_pink",
  "marigold",
  "baby_pink",
  "lavender",
  "powder_blue",
  "mint_green",
  "rose_pink",
  "smoky_blue",
  "greige",
  "soft_navy",
  "mauve",
  "ice_blue",
  "terracotta",
  "mustard",
  "olive",
  "chocolate_brown",
  "brick_red",
  "khaki",
  "pumpkin",
  "moss_green",
  "beige",
  "camel",
  "royal_blue",
  "pure_white",
  "black",
  "magenta",
  "emerald_green",
  "purple",
  "cherry_red",
  "silver_gray",
  "wine_red",
  "lemon_yellow",
] as const;
